
[env:esp32s3_debug]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

[env:esp32s3_release]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_flags = -DESP32STATE_DISABLE_LOGGING
